### ISSUE TITLE
make app config files loader

### ISSUE THREAD

**Issue by michalecznik123** [michalecznik123/linux-distro#3]
napisz skrypt ładujący i segregujący informacje o aplikacjach w systemie z /usr/share/applications.

**Comment by goodbit22** [comment]
chcesz to w  postaci  shell skryptu ?

**Comment by michalecznik123** [comment]
> 
> 
> chcesz to w postaci shell skryptu ?

już się tym zająłem i robię to w postaci skryptu pythona generalnie tym projektem chciałbym się zająć ja
